# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

product_set_probability <- function(z, N, p) {
    .Call('_PRODBINOM_product_set_probability', PACKAGE = 'PRODBINOM', z, N, p)
}

product_set_cumulative_probability <- function(z, N, p) {
    .Call('_PRODBINOM_product_set_cumulative_probability', PACKAGE = 'PRODBINOM', z, N, p)
}

product_set_quantile <- function(x, N, p) {
    .Call('_PRODBINOM_product_set_quantile', PACKAGE = 'PRODBINOM', x, N, p)
}

